const schools = [
  {
    "name": "Logan Adolescent Day Program",
    "campus": "Logan",
    "address": "Level 1, 55 Wembley Rd, Logan Central QLD",
    "area": "Logan",
    "type": "Adolescent Day Program",
    "minYear": null,
    "maxYear": null,
    "minAge": 13,
    "maxAge": 18,
    "gender": "Not stated",
    "phone": "07 3489 2600",
    "website": "https://refer.metrosouth.health.qld.gov.au/services/all/logan-adolescent-day-program",
    "delivery": [
      "In person"
    ],
    "sourcePage": 2,
    "approximate": false,
    "mappable": true,
    "notes": "Mental Health and Department of Education partnership; supports re-engagement with education.",
    "geocodeQuery": "Level 1, 55 Wembley Rd, Logan Central QLD",
    "fallbackQuery": "",
    "shortName": "Logan Adolescent Day Program – Logan"
  },
  {
    "name": "Yangah Adolescent Day Program",
    "campus": "Gold Coast",
    "address": "Robina Hospital, F2 Block, Bayberry Lane, Robina QLD",
    "area": "Gold Coast",
    "type": "Adolescent Day Program",
    "minYear": null,
    "maxYear": null,
    "minAge": 13,
    "maxAge": 18,
    "gender": "Not stated",
    "phone": "07 5629 1240",
    "website": "https://www.goldcoast.health.qld.gov.au/referrals/services/yangah-adolescent-day-program-13-18-years-cymhs",
    "delivery": [
      "In person"
    ],
    "sourcePage": 2,
    "approximate": false,
    "mappable": true,
    "notes": "Mental Health and Department of Education partnership; supports re-engagement with education.",
    "geocodeQuery": "Robina Hospital Bayberry Lane Robina QLD",
    "fallbackQuery": "",
    "shortName": "Yangah Adolescent Day Program – Gold Coast"
  },
  {
    "name": "Autism Queensland School",
    "campus": "Brighton Campus",
    "address": "136 North Rd, Brighton QLD",
    "area": "Brisbane",
    "type": "Specialist school",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "3631 6300",
    "website": "https://autismqld.com.au/services/school-aged/autism-queensland-school/",
    "delivery": [
      "Full time",
      "Part time"
    ],
    "sourcePage": 3,
    "approximate": false,
    "mappable": true,
    "notes": "AQ School offers full-time, part-time and distance education. PDF does not state year levels for these physical campuses.",
    "geocodeQuery": "136 North Rd, Brighton QLD",
    "fallbackQuery": "",
    "shortName": "Autism Queensland School – Brighton Campus"
  },
  {
    "name": "Autism Queensland School",
    "campus": "Sunnybank Hills Campus",
    "address": "437 Hellawell Road, Sunnybank Hills QLD",
    "area": "Brisbane",
    "type": "Specialist school",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "3540 8627",
    "website": "https://autismqld.com.au/services/school-aged/autism-queensland-school/",
    "delivery": [
      "Full time",
      "Part time"
    ],
    "sourcePage": 3,
    "approximate": false,
    "mappable": true,
    "notes": "AQ School offers full-time, part-time and distance education. PDF does not state year levels for these physical campuses.",
    "geocodeQuery": "437 Hellawell Road, Sunnybank Hills QLD",
    "fallbackQuery": "",
    "shortName": "Autism Queensland School – Sunnybank Hills Campus"
  },
  {
    "name": "Autism Queensland School",
    "campus": "Brightwater Campus",
    "address": "18 Freshwater St, Mountain Creek QLD",
    "area": "Sunshine Coast",
    "type": "Specialist school",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "3273 0000",
    "website": "https://autismqld.com.au/services/school-aged/autism-queensland-school/",
    "delivery": [
      "Full time",
      "Part time"
    ],
    "sourcePage": 3,
    "approximate": false,
    "mappable": true,
    "notes": "AQ School offers full-time, part-time and distance education. PDF does not state year levels for these physical campuses.",
    "geocodeQuery": "18 Freshwater St, Mountain Creek QLD",
    "fallbackQuery": "",
    "shortName": "Autism Queensland School – Brightwater Campus"
  },
  {
    "name": "Autism Queensland School",
    "campus": "Distance Education",
    "address": "",
    "area": "Queensland-wide",
    "type": "Distance education",
    "minYear": 3,
    "maxYear": 6,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "",
    "website": "https://autismqld.com.au/services/school-aged/autism-queensland-school/",
    "delivery": [
      "Distance education"
    ],
    "sourcePage": 3,
    "approximate": false,
    "mappable": false,
    "notes": "PDF states limited vacancies in Years 3–6 for the 2024 school year and priority for remote/regional students.",
    "geocodeQuery": "",
    "fallbackQuery": "",
    "shortName": "Autism Queensland School – Distance Education"
  },
  {
    "name": "Arcadia College",
    "campus": "Robina",
    "address": "12 Centreline Place, Robina QLD",
    "area": "Gold Coast",
    "type": "Special Assistance School",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Co-educational",
    "phone": "07 5655 1800",
    "website": "https://arcadia.qld.edu.au",
    "delivery": [
      "In person",
      "Distance education"
    ],
    "sourcePage": 4,
    "approximate": false,
    "mappable": true,
    "notes": "Co-educational special assistance secondary school. Distance Education is Years 8–12; PDF does not state a year range for the in-person campus.",
    "geocodeQuery": "12 Centreline Place, Robina QLD",
    "fallbackQuery": "",
    "shortName": "Arcadia College – Robina"
  },
  {
    "name": "Arethusa College",
    "campus": "Deception Bay",
    "address": "Deception Bay, QLD — exact street address not provided in PDF",
    "area": "Moreton Bay",
    "type": "Alternative education",
    "minYear": 7,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 2000 0200",
    "website": "https://www.arethusa.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 5,
    "approximate": true,
    "mappable": true,
    "notes": "Alternative educational and vocational pathways for Years 7–12.",
    "geocodeQuery": "Arethusa College Deception Bay QLD",
    "fallbackQuery": "Deception Bay QLD",
    "shortName": "Arethusa College – Deception Bay"
  },
  {
    "name": "Arethusa College",
    "campus": "Spring Hill",
    "address": "Spring Hill, QLD — exact street address not provided in PDF",
    "area": "Brisbane",
    "type": "Alternative education",
    "minYear": 7,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 2000 0200",
    "website": "https://www.arethusa.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 5,
    "approximate": true,
    "mappable": true,
    "notes": "Alternative educational and vocational pathways for Years 7–12.",
    "geocodeQuery": "Arethusa College Spring Hill QLD",
    "fallbackQuery": "Spring Hill QLD",
    "shortName": "Arethusa College – Spring Hill"
  },
  {
    "name": "Arethusa College",
    "campus": "West End (Montague Road)",
    "address": "West End (Montague Road), QLD — exact street address not provided in PDF",
    "area": "Brisbane",
    "type": "Alternative education",
    "minYear": 7,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 2000 0200",
    "website": "https://www.arethusa.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 5,
    "approximate": true,
    "mappable": true,
    "notes": "Alternative educational and vocational pathways for Years 7–12.",
    "geocodeQuery": "Arethusa College Montague Road West End QLD",
    "fallbackQuery": "West End QLD",
    "shortName": "Arethusa College – West End (Montague Road)"
  },
  {
    "name": "Arethusa College",
    "campus": "Forest Lake",
    "address": "Forest Lake, QLD — exact street address not provided in PDF",
    "area": "Brisbane",
    "type": "Alternative education",
    "minYear": 7,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 2000 0200",
    "website": "https://www.arethusa.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 5,
    "approximate": true,
    "mappable": true,
    "notes": "Alternative educational and vocational pathways for Years 7–12.",
    "geocodeQuery": "Arethusa College Forest Lake QLD",
    "fallbackQuery": "Forest Lake QLD",
    "shortName": "Arethusa College – Forest Lake"
  },
  {
    "name": "Arethusa College",
    "campus": "Maroochydore",
    "address": "Maroochydore, QLD — exact street address not provided in PDF",
    "area": "Sunshine Coast",
    "type": "Alternative education",
    "minYear": 7,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 2000 0200",
    "website": "https://www.arethusa.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 5,
    "approximate": true,
    "mappable": true,
    "notes": "Alternative educational and vocational pathways for Years 7–12.",
    "geocodeQuery": "Arethusa College Maroochydore QLD",
    "fallbackQuery": "Maroochydore QLD",
    "shortName": "Arethusa College – Maroochydore"
  },
  {
    "name": "Arethusa College",
    "campus": "Windsor",
    "address": "Windsor, QLD — exact street address not provided in PDF",
    "area": "Brisbane",
    "type": "Alternative education",
    "minYear": 7,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 2000 0200",
    "website": "https://www.arethusa.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 5,
    "approximate": true,
    "mappable": true,
    "notes": "Alternative educational and vocational pathways for Years 7–12.",
    "geocodeQuery": "Arethusa College Windsor QLD",
    "fallbackQuery": "Windsor QLD",
    "shortName": "Arethusa College – Windsor"
  },
  {
    "name": "Arethusa College",
    "campus": "Caboolture",
    "address": "Caboolture, QLD — exact street address not provided in PDF",
    "area": "Moreton Bay",
    "type": "Alternative education",
    "minYear": 7,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 2000 0200",
    "website": "https://www.arethusa.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 5,
    "approximate": true,
    "mappable": true,
    "notes": "Alternative educational and vocational pathways for Years 7–12.",
    "geocodeQuery": "Arethusa College Caboolture QLD",
    "fallbackQuery": "Caboolture QLD",
    "shortName": "Arethusa College – Caboolture"
  },
  {
    "name": "Arethusa College",
    "campus": "Ipswich",
    "address": "Ipswich, QLD — exact street address not provided in PDF",
    "area": "Ipswich",
    "type": "Alternative education",
    "minYear": 7,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 2000 0200",
    "website": "https://www.arethusa.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 5,
    "approximate": true,
    "mappable": true,
    "notes": "Alternative educational and vocational pathways for Years 7–12.",
    "geocodeQuery": "Arethusa College Ipswich QLD",
    "fallbackQuery": "Ipswich QLD",
    "shortName": "Arethusa College – Ipswich"
  },
  {
    "name": "Arethusa College",
    "campus": "Springwood",
    "address": "Springwood, QLD — exact street address not provided in PDF",
    "area": "Logan",
    "type": "Alternative education",
    "minYear": 7,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 2000 0200",
    "website": "https://www.arethusa.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 5,
    "approximate": true,
    "mappable": true,
    "notes": "Alternative educational and vocational pathways for Years 7–12.",
    "geocodeQuery": "Arethusa College Springwood QLD",
    "fallbackQuery": "Springwood QLD",
    "shortName": "Arethusa College – Springwood"
  },
  {
    "name": "Arethusa College",
    "campus": "Berrinba",
    "address": "Berrinba, QLD — exact street address not provided in PDF",
    "area": "Logan",
    "type": "Alternative education",
    "minYear": 7,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 2000 0200",
    "website": "https://www.arethusa.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 5,
    "approximate": true,
    "mappable": true,
    "notes": "Alternative educational and vocational pathways for Years 7–12.",
    "geocodeQuery": "Arethusa College Berrinba QLD",
    "fallbackQuery": "Berrinba QLD",
    "shortName": "Arethusa College – Berrinba"
  },
  {
    "name": "Arethusa College",
    "campus": "Anywhere Learning Team",
    "address": "",
    "area": "Queensland-wide",
    "type": "Alternative education",
    "minYear": 7,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 2000 0200",
    "website": "https://www.arethusa.qld.edu.au/",
    "delivery": [
      "Remote/flexible"
    ],
    "sourcePage": 5,
    "approximate": false,
    "mappable": false,
    "notes": "Listed in the PDF alongside Arethusa campuses; no physical address is provided.",
    "geocodeQuery": "",
    "fallbackQuery": "",
    "shortName": "Arethusa College – Anywhere Learning Team"
  },
  {
    "name": "The BUSY School",
    "campus": "Brisbane City",
    "address": "Level 2, 410 Ann St, Brisbane QLD",
    "area": "Brisbane",
    "type": "Special Assistance School",
    "minYear": 11,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 5585 4383",
    "website": "https://www.busyschools.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 6,
    "approximate": false,
    "mappable": true,
    "notes": "Alternative Years 11–12 special assistance school; career, vocational or tertiary support and work-readiness skills.",
    "geocodeQuery": "Level 2, 410 Ann St, Brisbane QLD",
    "fallbackQuery": "",
    "shortName": "The BUSY School – Brisbane City"
  },
  {
    "name": "The BUSY School",
    "campus": "Cleveland",
    "address": "32 Enterprise St, Cleveland QLD",
    "area": "Redlands",
    "type": "Special Assistance School",
    "minYear": 11,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3899 7122",
    "website": "https://www.busyschools.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 6,
    "approximate": false,
    "mappable": true,
    "notes": "Alternative Years 11–12 special assistance school; career, vocational or tertiary support and work-readiness skills.",
    "geocodeQuery": "32 Enterprise St, Cleveland QLD",
    "fallbackQuery": "",
    "shortName": "The BUSY School – Cleveland"
  },
  {
    "name": "The BUSY School",
    "campus": "Coolangatta",
    "address": "5 Scott St, Coolangatta QLD",
    "area": "Gold Coast",
    "type": "Special Assistance School",
    "minYear": 11,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 5506 2602",
    "website": "https://www.busyschools.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 6,
    "approximate": false,
    "mappable": true,
    "notes": "Alternative Years 11–12 special assistance school; career, vocational or tertiary support and work-readiness skills.",
    "geocodeQuery": "5 Scott St, Coolangatta QLD",
    "fallbackQuery": "",
    "shortName": "The BUSY School – Coolangatta"
  },
  {
    "name": "The BUSY School",
    "campus": "Ipswich",
    "address": "62 East St, Ipswich QLD",
    "area": "Ipswich",
    "type": "Special Assistance School",
    "minYear": 11,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3810 9150",
    "website": "https://www.busyschools.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 6,
    "approximate": false,
    "mappable": true,
    "notes": "Alternative Years 11–12 special assistance school; career, vocational or tertiary support and work-readiness skills.",
    "geocodeQuery": "62 East St, Ipswich QLD",
    "fallbackQuery": "",
    "shortName": "The BUSY School – Ipswich"
  },
  {
    "name": "The BUSY School",
    "campus": "Salisbury",
    "address": "460-492 Beaudesert Rd, Salisbury QLD",
    "area": "Brisbane",
    "type": "Special Assistance School",
    "minYear": 11,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3440 4271",
    "website": "https://www.busyschools.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 6,
    "approximate": false,
    "mappable": true,
    "notes": "Alternative Years 11–12 special assistance school; career, vocational or tertiary support and work-readiness skills.",
    "geocodeQuery": "460-492 Beaudesert Rd, Salisbury QLD",
    "fallbackQuery": "",
    "shortName": "The BUSY School – Salisbury"
  },
  {
    "name": "The BUSY School",
    "campus": "Shailer Park",
    "address": "37-43 Commercial Drive, Shailer Park QLD",
    "area": "Logan",
    "type": "Special Assistance School",
    "minYear": 11,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3440 4241",
    "website": "https://www.busyschools.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 6,
    "approximate": false,
    "mappable": true,
    "notes": "Alternative Years 11–12 special assistance school; career, vocational or tertiary support and work-readiness skills.",
    "geocodeQuery": "37-43 Commercial Drive, Shailer Park QLD",
    "fallbackQuery": "",
    "shortName": "The BUSY School – Shailer Park"
  },
  {
    "name": "The BUSY School",
    "campus": "Southport Girls+",
    "address": "137-139 Nerang St, Southport QLD",
    "area": "Gold Coast",
    "type": "Special Assistance School",
    "minYear": 11,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Girls",
    "phone": "07 5508 4055",
    "website": "https://www.busyschools.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 6,
    "approximate": false,
    "mappable": true,
    "notes": "Alternative Years 11–12 special assistance school; career, vocational or tertiary support and work-readiness skills.",
    "geocodeQuery": "137-139 Nerang St, Southport QLD",
    "fallbackQuery": "",
    "shortName": "The BUSY School – Southport Girls+"
  },
  {
    "name": "The BUSY School",
    "campus": "Strathpine",
    "address": "219 Gympie Road, Strathpine QLD",
    "area": "Moreton Bay",
    "type": "Special Assistance School",
    "minYear": 11,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3624 8900",
    "website": "https://www.busyschools.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 6,
    "approximate": false,
    "mappable": true,
    "notes": "Alternative Years 11–12 special assistance school; career, vocational or tertiary support and work-readiness skills.",
    "geocodeQuery": "219 Gympie Road, Strathpine QLD",
    "fallbackQuery": "",
    "shortName": "The BUSY School – Strathpine"
  },
  {
    "name": "Carbrook Animal Assisted Learning Centre",
    "campus": "Carbrook",
    "address": "597-605 Beenleigh Redland Bay Road, Carbrook QLD",
    "area": "Logan",
    "type": "Special Assistance School",
    "minYear": 7,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3557 2117",
    "website": "https://www.carbrookcentre.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 7,
    "approximate": false,
    "mappable": true,
    "notes": "Independent Special Assistance School for Years 7–12; incorporates animal-assisted learning.",
    "geocodeQuery": "597-605 Beenleigh Redland Bay Road, Carbrook QLD",
    "fallbackQuery": "",
    "shortName": "Carbrook Animal Assisted Learning Centre – Carbrook"
  },
  {
    "name": "Carinity Education Southside",
    "campus": "Sunnybank",
    "address": "153 Lister St, Sunnybank QLD",
    "area": "Brisbane",
    "type": "Special Assistance School",
    "minYear": 7,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Girls",
    "phone": "07 3423 7499",
    "website": "https://carinity.qld.edu.au/southside/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 8,
    "approximate": false,
    "mappable": true,
    "notes": "Girls program for Years 7–10 and Years 11–12. PDF also notes Carinity campuses in other Queensland cities without addresses.",
    "geocodeQuery": "153 Lister St, Sunnybank QLD",
    "fallbackQuery": "",
    "shortName": "Carinity Education Southside – Sunnybank"
  },
  {
    "name": "The Clear Skies Project",
    "campus": "Coolangatta",
    "address": "30a Griffith Street, Coolangatta QLD 4225",
    "area": "Gold Coast",
    "type": "Youth re-engagement program",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "0426 728 820",
    "website": "https://theclearskiesproject.com/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 8,
    "approximate": false,
    "mappable": true,
    "notes": "Supports disengaged young people to re-engage or transition to work/training; 6–7 spots per program.",
    "geocodeQuery": "30a Griffith Street, Coolangatta QLD 4225",
    "fallbackQuery": "",
    "shortName": "The Clear Skies Project – Coolangatta"
  },
  {
    "name": "Eagleby Learning Centre",
    "campus": "Eagleby Learning Campus",
    "address": "161 Herses Road, Eagleby QLD",
    "area": "Logan",
    "type": "Flexible learning centre",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "3382 9222",
    "website": "https://eaglebylc.eq.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 9,
    "approximate": false,
    "mappable": true,
    "notes": "Education Queensland facility offering education and training programs to school-age and mature-age students.",
    "geocodeQuery": "161 Herses Road, Eagleby QLD",
    "fallbackQuery": "",
    "shortName": "Eagleby Learning Centre – Eagleby Learning Campus"
  },
  {
    "name": "Eagleby Learning Centre",
    "campus": "Helensvale Learning Campus",
    "address": "Lower Level M1 Building, 120 Siganto Drive, Helensvale QLD",
    "area": "Gold Coast",
    "type": "Flexible learning centre",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "5562 9888",
    "website": "https://eaglebylc.eq.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 9,
    "approximate": false,
    "mappable": true,
    "notes": "Education Queensland facility offering education and training programs to school-age and mature-age students.",
    "geocodeQuery": "Lower Level M1 Building, 120 Siganto Drive, Helensvale QLD",
    "fallbackQuery": "",
    "shortName": "Eagleby Learning Centre – Helensvale Learning Campus"
  },
  {
    "name": "Eagleby Learning Centre",
    "campus": "Varsity Lakes Learning Campus",
    "address": "Ground floor, 183 Varsity Parade, Varsity Lakes QLD",
    "area": "Gold Coast",
    "type": "Flexible learning centre",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "5553 8300",
    "website": "https://eaglebylc.eq.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 9,
    "approximate": false,
    "mappable": true,
    "notes": "Education Queensland facility offering education and training programs to school-age and mature-age students.",
    "geocodeQuery": "Ground floor, 183 Varsity Parade, Varsity Lakes QLD",
    "fallbackQuery": "",
    "shortName": "Eagleby Learning Centre – Varsity Lakes Learning Campus"
  },
  {
    "name": "Edmund Rice Flexible Learning Centres",
    "campus": "Southport Flexible Learning Centre",
    "address": "2 Nakina St, Southport QLD",
    "area": "Gold Coast",
    "type": "Flexible learning centre",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 5657 8950",
    "website": "https://www.erea.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 10,
    "approximate": false,
    "mappable": true,
    "notes": "Flexible learning centre. PDF does not state a year range for the Southport campus.",
    "geocodeQuery": "2 Nakina St, Southport QLD",
    "fallbackQuery": "",
    "shortName": "Edmund Rice Flexible Learning Centres – Southport Flexible Learning Centre"
  },
  {
    "name": "Edmund Rice Flexible Learning Centres",
    "campus": "Centre Education Program Kingston",
    "address": "108 Mudgee St, Kingston QLD",
    "area": "Logan",
    "type": "Flexible learning centre",
    "minYear": 7,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3808 6800",
    "website": "https://www.erea.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 10,
    "approximate": false,
    "mappable": true,
    "notes": "Secondary school offering educational pathways for young people in Years 7–12 who have difficulty accessing school.",
    "geocodeQuery": "108 Mudgee St, Kingston QLD",
    "fallbackQuery": "",
    "shortName": "Edmund Rice Flexible Learning Centres – Centre Education Program Kingston"
  },
  {
    "name": "Everything Suarve INC (E-S)",
    "campus": "",
    "address": "",
    "area": "Not stated",
    "type": "Youth support program",
    "minYear": null,
    "maxYear": null,
    "minAge": 16,
    "maxAge": 24,
    "gender": "Not stated",
    "phone": "07 5612 7301",
    "website": "https://www.esuarve.com.au/",
    "delivery": [],
    "sourcePage": 11,
    "approximate": false,
    "mappable": false,
    "notes": "Not-for-profit early intervention program for young people aged 16–24. No physical location is supplied in the PDF.",
    "geocodeQuery": "",
    "fallbackQuery": "",
    "shortName": "Everything Suarve INC (E-S)"
  },
  {
    "name": "Faith Christian School Distance Education",
    "campus": "Distance Education",
    "address": "",
    "area": "Queensland-wide",
    "type": "Distance education",
    "minYear": 0,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3059 1881",
    "website": "https://faith.qld.edu.au/",
    "delivery": [
      "Distance education"
    ],
    "sourcePage": 11,
    "approximate": false,
    "mappable": false,
    "notes": "Prep to Year 12; online lessons, camps, workshops, learning support and resources. PDF supplies PO Box 105 Kingston rather than a physical campus address.",
    "geocodeQuery": "",
    "fallbackQuery": "",
    "shortName": "Faith Christian School Distance Education – Distance Education"
  },
  {
    "name": "Flourish Education",
    "campus": "Tugun",
    "address": "1/1 Kallara St, Tugun QLD",
    "area": "Gold Coast",
    "type": "Education support service",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "0434 594 764",
    "website": "https://flourisheducation.com.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 12,
    "approximate": false,
    "mappable": true,
    "notes": "Education and disability support services for young people of all ages; supports home schoolers and flexible enrolment solutions.",
    "geocodeQuery": "1/1 Kallara St, Tugun QLD",
    "fallbackQuery": "",
    "shortName": "Flourish Education – Tugun"
  },
  {
    "name": "Home Education Unit, Education Queensland",
    "campus": "Brisbane",
    "address": "Education House, 30 Mary Street, Brisbane QLD",
    "area": "Brisbane",
    "type": "Home education support",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3513 6755 / 1800 677 176",
    "website": "https://education.qld.gov.au/schools-educators/other-education/home-education",
    "delivery": [
      "Support/service"
    ],
    "sourcePage": 12,
    "approximate": false,
    "mappable": true,
    "notes": "Education Queensland Home Education Unit; policy and procedure information for staff.",
    "geocodeQuery": "Education House, 30 Mary Street, Brisbane QLD",
    "fallbackQuery": "",
    "shortName": "Home Education Unit, Education Queensland – Brisbane"
  },
  {
    "name": "Hymba Yumba Independent School",
    "campus": "Springfield",
    "address": "6 Springfield Pkwy, Springfield QLD",
    "area": "Ipswich",
    "type": "Independent school",
    "minYear": 0,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3381 8134",
    "website": "https://hyis.qld.edu.au/contact-us/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 13,
    "approximate": false,
    "mappable": true,
    "notes": "Co-educational Preparatory to Year 12 program; First Nations school.",
    "geocodeQuery": "6 Springfield Pkwy, Springfield QLD",
    "fallbackQuery": "",
    "shortName": "Hymba Yumba Independent School – Springfield"
  },
  {
    "name": "Indie School",
    "campus": "Logan Campus",
    "address": "75-87 Grand Plaza Drive, Browns Plains QLD",
    "area": "Logan",
    "type": "Alternative high school",
    "minYear": 9,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "1800 046 343",
    "website": "https://indieschool.edu.au/campus/logan/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 13,
    "approximate": false,
    "mappable": true,
    "notes": "Independent alternative high school for Years 9–12.",
    "geocodeQuery": "75-87 Grand Plaza Drive, Browns Plains QLD",
    "fallbackQuery": "",
    "shortName": "Indie School – Logan Campus"
  },
  {
    "name": "Indie School",
    "campus": "Ipswich Campus",
    "address": "Ipswich, QLD — exact street address not provided in PDF",
    "area": "Ipswich",
    "type": "Alternative high school",
    "minYear": 9,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "1800 046 343",
    "website": "https://indieschool.edu.au/campus/logan/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 13,
    "approximate": true,
    "mappable": true,
    "notes": "PDF states Indie School also has a campus here but does not provide its street address.",
    "geocodeQuery": "Indie School Ipswich QLD",
    "fallbackQuery": "Ipswich QLD",
    "shortName": "Indie School – Ipswich Campus"
  },
  {
    "name": "Indie School",
    "campus": "Brisbane City Campus",
    "address": "Brisbane City, QLD — exact street address not provided in PDF",
    "area": "Brisbane",
    "type": "Alternative high school",
    "minYear": 9,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "1800 046 343",
    "website": "https://indieschool.edu.au/campus/logan/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 13,
    "approximate": true,
    "mappable": true,
    "notes": "PDF states Indie School also has a campus here but does not provide its street address.",
    "geocodeQuery": "Indie School Brisbane City QLD",
    "fallbackQuery": "Brisbane City QLD",
    "shortName": "Indie School – Brisbane City Campus"
  },
  {
    "name": "Kingston Centre for Continued Secondary Education",
    "campus": "Kingston",
    "address": "62 Bega Road, Kingston QLD 4114",
    "area": "Logan",
    "type": "Flexible secondary education",
    "minYear": 10,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3826 1388",
    "website": "https://kingstonccse.eq.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 14,
    "approximate": false,
    "mappable": true,
    "notes": "Offers Year 10 Maths/English and Years 11–12 programs; also Kickstart and Bridge options.",
    "geocodeQuery": "62 Bega Road, Kingston QLD 4114",
    "fallbackQuery": "",
    "shortName": "Kingston Centre for Continued Secondary Education – Kingston"
  },
  {
    "name": "Mastery Schools Australia",
    "campus": "Coolangatta",
    "address": "Level 1, 72-80 Marine Parade, Coolangatta QLD",
    "area": "Gold Coast",
    "type": "Alternative/specialist school",
    "minYear": 4,
    "maxYear": 10,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "5551 4080",
    "website": "https://msa.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 15,
    "approximate": false,
    "mappable": true,
    "notes": "Caters for Years 4–10; Australian Curriculum; school size capped at 300.",
    "geocodeQuery": "Level 1, 72-80 Marine Parade, Coolangatta QLD",
    "fallbackQuery": "",
    "shortName": "Mastery Schools Australia – Coolangatta"
  },
  {
    "name": "Mastery Schools Australia",
    "campus": "Southport",
    "address": "105 Scarborough St, Southport QLD",
    "area": "Gold Coast",
    "type": "Alternative/specialist school",
    "minYear": 4,
    "maxYear": 10,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "5689 3553",
    "website": "https://msa.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 15,
    "approximate": false,
    "mappable": true,
    "notes": "Caters for Years 4–10; Australian Curriculum; school size capped at 300.",
    "geocodeQuery": "105 Scarborough St, Southport QLD",
    "fallbackQuery": "",
    "shortName": "Mastery Schools Australia – Southport"
  },
  {
    "name": "Mastery Schools Australia",
    "campus": "Springfield",
    "address": "37 Sinnathamby Blvd, Springfield Central QLD",
    "area": "Ipswich",
    "type": "Alternative/specialist school",
    "minYear": 4,
    "maxYear": 10,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "3870 4690",
    "website": "https://msa.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 15,
    "approximate": false,
    "mappable": true,
    "notes": "Caters for Years 4–10; Australian Curriculum; school size capped at 300.",
    "geocodeQuery": "37 Sinnathamby Blvd, Springfield Central QLD",
    "fallbackQuery": "",
    "shortName": "Mastery Schools Australia – Springfield"
  },
  {
    "name": "Mastery Schools Australia",
    "campus": "Varsity Lakes",
    "address": "15 Lake St, Varsity Lakes QLD",
    "area": "Gold Coast",
    "type": "Alternative/specialist school",
    "minYear": 4,
    "maxYear": 10,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "5513 1434",
    "website": "https://msa.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 15,
    "approximate": false,
    "mappable": true,
    "notes": "Caters for Years 4–10; Australian Curriculum; school size capped at 300.",
    "geocodeQuery": "15 Lake St, Varsity Lakes QLD",
    "fallbackQuery": "",
    "shortName": "Mastery Schools Australia – Varsity Lakes"
  },
  {
    "name": "Mastery Schools Australia",
    "campus": "West Brisbane",
    "address": "Building 3, Level 2, 53 Prospect Rd, Gaythorne QLD",
    "area": "Brisbane",
    "type": "Alternative/specialist school",
    "minYear": 4,
    "maxYear": 10,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "2115 7009",
    "website": "https://msa.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 15,
    "approximate": false,
    "mappable": true,
    "notes": "Caters for Years 4–10; Australian Curriculum; school size capped at 300.",
    "geocodeQuery": "Building 3, Level 2, 53 Prospect Rd, Gaythorne QLD",
    "fallbackQuery": "",
    "shortName": "Mastery Schools Australia – West Brisbane"
  },
  {
    "name": "Men of Business (MOB) Academy",
    "campus": "Southport",
    "address": "5 Nerang St, Southport QLD",
    "area": "Gold Coast",
    "type": "Alternative high school",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Boys/young men",
    "phone": "07 5613 2093",
    "website": "https://menofbusiness.com.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 16,
    "approximate": false,
    "mappable": true,
    "notes": "Alternative high school support for young men; PDF does not state year levels.",
    "geocodeQuery": "5 Nerang St, Southport QLD",
    "fallbackQuery": "",
    "shortName": "Men of Business (MOB) Academy – Southport"
  },
  {
    "name": "Ohana College",
    "campus": "Meadowbrook",
    "address": "Building L15, Griffith University, Facilities Lane, Meadowbrook QLD",
    "area": "Logan",
    "type": "Special Assistance School",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Co-educational",
    "phone": "07 2800 6300",
    "website": "https://ohanacollege.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 16,
    "approximate": false,
    "mappable": true,
    "notes": "Co-educational special assistance secondary school aligned to Australian Curriculum; sister school to Arcadia.",
    "geocodeQuery": "Building L15, Griffith University, Facilities Lane, Meadowbrook QLD",
    "fallbackQuery": "",
    "shortName": "Ohana College – Meadowbrook"
  },
  {
    "name": "Queensland Pathways State College",
    "campus": "Bracken Ridge",
    "address": "C Block Bracken Ridge TAFE, 157 Norris Rd, Bracken Ridge QLD",
    "area": "Brisbane",
    "type": "State school / senior transitions",
    "minYear": 10,
    "maxYear": 12,
    "minAge": 15,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3421 0666",
    "website": "https://qpsc.eq.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 17,
    "approximate": false,
    "mappable": true,
    "notes": "Senior transitions program for Years 10–12; students must be at least 15 and face significant barriers accessing mainstream education.",
    "geocodeQuery": "C Block Bracken Ridge TAFE, 157 Norris Rd, Bracken Ridge QLD",
    "fallbackQuery": "",
    "shortName": "Queensland Pathways State College – Bracken Ridge"
  },
  {
    "name": "Queensland Pathways State College",
    "campus": "Bundamba",
    "address": "D Block Bundamba TAFE, Mary and Byrne St, Bundamba QLD",
    "area": "Ipswich",
    "type": "State school / senior transitions",
    "minYear": 10,
    "maxYear": 12,
    "minAge": 15,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3421 0666",
    "website": "https://qpsc.eq.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 17,
    "approximate": false,
    "mappable": true,
    "notes": "Senior transitions program for Years 10–12; students must be at least 15 and face significant barriers accessing mainstream education.",
    "geocodeQuery": "D Block Bundamba TAFE, Mary and Byrne St, Bundamba QLD",
    "fallbackQuery": "",
    "shortName": "Queensland Pathways State College – Bundamba"
  },
  {
    "name": "Queensland Pathways State College",
    "campus": "Coorparoo",
    "address": "347 Old Cleveland Rd, Coorparoo QLD",
    "area": "Brisbane",
    "type": "State school / senior transitions",
    "minYear": 10,
    "maxYear": 12,
    "minAge": 15,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3421 0666",
    "website": "https://qpsc.eq.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 17,
    "approximate": false,
    "mappable": true,
    "notes": "Senior transitions program for Years 10–12; students must be at least 15 and face significant barriers accessing mainstream education.",
    "geocodeQuery": "347 Old Cleveland Rd, Coorparoo QLD",
    "fallbackQuery": "",
    "shortName": "Queensland Pathways State College – Coorparoo"
  },
  {
    "name": "Queensland Pathways State College",
    "campus": "Goodna",
    "address": "45 Queen St, Goodna QLD",
    "area": "Ipswich",
    "type": "State school / senior transitions",
    "minYear": 10,
    "maxYear": 12,
    "minAge": 15,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3421 0666",
    "website": "https://qpsc.eq.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 17,
    "approximate": false,
    "mappable": true,
    "notes": "Senior transitions program for Years 10–12; students must be at least 15 and face significant barriers accessing mainstream education.",
    "geocodeQuery": "45 Queen St, Goodna QLD",
    "fallbackQuery": "",
    "shortName": "Queensland Pathways State College – Goodna"
  },
  {
    "name": "Queensland Pathways State College",
    "campus": "Moreton Bay",
    "address": "109 School Rd, Kallangur QLD",
    "area": "Moreton Bay",
    "type": "State school / senior transitions",
    "minYear": 10,
    "maxYear": 12,
    "minAge": 15,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3421 0666",
    "website": "https://qpsc.eq.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 17,
    "approximate": false,
    "mappable": true,
    "notes": "Senior transitions program for Years 10–12; students must be at least 15 and face significant barriers accessing mainstream education.",
    "geocodeQuery": "109 School Rd, Kallangur QLD",
    "fallbackQuery": "",
    "shortName": "Queensland Pathways State College – Moreton Bay"
  },
  {
    "name": "Queensland Pathways State College",
    "campus": "Mount Gravatt",
    "address": "H Block Mt Gravatt TAFE, 1030 Cavendish Rd, Mount Gravatt QLD",
    "area": "Brisbane",
    "type": "State school / senior transitions",
    "minYear": 10,
    "maxYear": 12,
    "minAge": 15,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3421 0666",
    "website": "https://qpsc.eq.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 17,
    "approximate": false,
    "mappable": true,
    "notes": "Senior transitions program for Years 10–12; students must be at least 15 and face significant barriers accessing mainstream education.",
    "geocodeQuery": "H Block Mt Gravatt TAFE, 1030 Cavendish Rd, Mount Gravatt QLD",
    "fallbackQuery": "",
    "shortName": "Queensland Pathways State College – Mount Gravatt"
  },
  {
    "name": "Queensland Pathways State College",
    "campus": "Toowoomba",
    "address": "Lot 42, Hursley Rd, Newtown QLD",
    "area": "Toowoomba",
    "type": "State school / senior transitions",
    "minYear": 10,
    "maxYear": 12,
    "minAge": 15,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3421 0666",
    "website": "https://qpsc.eq.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 17,
    "approximate": false,
    "mappable": true,
    "notes": "Senior transitions program for Years 10–12; students must be at least 15 and face significant barriers accessing mainstream education.",
    "geocodeQuery": "Lot 42, Hursley Rd, Newtown QLD",
    "fallbackQuery": "",
    "shortName": "Queensland Pathways State College – Toowoomba"
  },
  {
    "name": "Brisbane School of Distance Education",
    "campus": "",
    "address": "",
    "area": "Brisbane",
    "type": "Distance education",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3727 2444",
    "website": "https://brisbanesde.eq.edu.au/",
    "delivery": [
      "Distance education"
    ],
    "sourcePage": 18,
    "approximate": false,
    "mappable": false,
    "notes": "Listed by the PDF; no physical address or year range is supplied on this page.",
    "geocodeQuery": "",
    "fallbackQuery": "",
    "shortName": "Brisbane School of Distance Education"
  },
  {
    "name": "Silkwood School",
    "campus": "Prep to Year 9 Campus",
    "address": "Mt Nathan, QLD — exact street address not provided in PDF",
    "area": "Gold Coast",
    "type": "Independent school",
    "minYear": 0,
    "maxYear": 9,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 5655 0300",
    "website": "https://www.silkwood.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 19,
    "approximate": true,
    "mappable": true,
    "notes": "Montessori-based independent school. PDF states the Prep–Year 9 campus is at Mt Nathan.",
    "geocodeQuery": "Silkwood School Mt Nathan QLD",
    "fallbackQuery": "Mt Nathan QLD",
    "shortName": "Silkwood School – Prep to Year 9 Campus"
  },
  {
    "name": "Silkwood School",
    "campus": "Senior School Campus",
    "address": "Robina, QLD — exact street address not provided in PDF",
    "area": "Gold Coast",
    "type": "Independent school",
    "minYear": 10,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 5655 0300",
    "website": "https://www.silkwood.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 19,
    "approximate": true,
    "mappable": true,
    "notes": "PDF states the Year 10–12 Senior School campus is located in Robina.",
    "geocodeQuery": "Silkwood School Senior School Robina QLD",
    "fallbackQuery": "Robina QLD",
    "shortName": "Silkwood School – Senior School Campus"
  },
  {
    "name": "The Village School – Gold Coast",
    "campus": "Coolangatta",
    "address": "Level 1, 91 Griffith St, Coolangatta QLD",
    "area": "Gold Coast",
    "type": "Independent/alternative primary school",
    "minYear": 0,
    "maxYear": 6,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "",
    "website": "https://thevillageschoolgoldcoast.com.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 19,
    "approximate": false,
    "mappable": true,
    "notes": "Prep–Year 6, multi-age; place-based learning and Australian Curriculum.",
    "geocodeQuery": "Level 1, 91 Griffith St, Coolangatta QLD",
    "fallbackQuery": "",
    "shortName": "The Village School – Gold Coast – Coolangatta"
  },
  {
    "name": "The Murri School",
    "campus": "Acacia Ridge",
    "address": "1277 Beaudesert Rd, Acacia Ridge QLD",
    "area": "Brisbane",
    "type": "Independent Community School",
    "minYear": 0,
    "maxYear": 12,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3255 6133",
    "website": "http://murrischool.qld.edu.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 20,
    "approximate": false,
    "mappable": true,
    "notes": "Independent Community School for Prep to Year 12; culture and community are central to its model.",
    "geocodeQuery": "1277 Beaudesert Rd, Acacia Ridge QLD",
    "fallbackQuery": "",
    "shortName": "The Murri School – Acacia Ridge"
  },
  {
    "name": "The Industry School",
    "campus": "Brisbane",
    "address": "88 Leichhardt St, Spring Hill QLD",
    "area": "Brisbane",
    "type": "Industry/vocational school",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3153 5100",
    "website": "https://theindustryschool.com.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 21,
    "approximate": false,
    "mappable": true,
    "notes": "The PDF provides campus locations and contact details but does not state year levels on this page.",
    "geocodeQuery": "88 Leichhardt St, Spring Hill QLD",
    "fallbackQuery": "",
    "shortName": "The Industry School – Brisbane"
  },
  {
    "name": "The Industry School",
    "campus": "Gold Coast",
    "address": "281 Scottsdale Drive, Robina QLD",
    "area": "Gold Coast",
    "type": "Industry/vocational school",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 5635 0400",
    "website": "https://theindustryschool.com.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 21,
    "approximate": false,
    "mappable": true,
    "notes": "The PDF provides campus locations and contact details but does not state year levels on this page.",
    "geocodeQuery": "281 Scottsdale Drive, Robina QLD",
    "fallbackQuery": "",
    "shortName": "The Industry School – Gold Coast"
  },
  {
    "name": "The Industry School",
    "campus": "Ipswich",
    "address": "17 Lowry St, North Ipswich QLD",
    "area": "Ipswich",
    "type": "Industry/vocational school",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3050 4800",
    "website": "https://theindustryschool.com.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 21,
    "approximate": false,
    "mappable": true,
    "notes": "The PDF provides campus locations and contact details but does not state year levels on this page.",
    "geocodeQuery": "17 Lowry St, North Ipswich QLD",
    "fallbackQuery": "",
    "shortName": "The Industry School – Ipswich"
  },
  {
    "name": "The Industry School",
    "campus": "Redlands",
    "address": "233 Middle St, Cleveland QLD",
    "area": "Redlands",
    "type": "Industry/vocational school",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3086 0500",
    "website": "https://theindustryschool.com.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 21,
    "approximate": false,
    "mappable": true,
    "notes": "The PDF provides campus locations and contact details but does not state year levels on this page.",
    "geocodeQuery": "233 Middle St, Cleveland QLD",
    "fallbackQuery": "",
    "shortName": "The Industry School – Redlands"
  },
  {
    "name": "The Industry School",
    "campus": "Toowoomba",
    "address": "1-3 Russell St, Toowoomba QLD",
    "area": "Toowoomba",
    "type": "Industry/vocational school",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 4592 8700",
    "website": "https://theindustryschool.com.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 21,
    "approximate": false,
    "mappable": true,
    "notes": "The PDF provides campus locations and contact details but does not state year levels on this page.",
    "geocodeQuery": "1-3 Russell St, Toowoomba QLD",
    "fallbackQuery": "",
    "shortName": "The Industry School – Toowoomba"
  },
  {
    "name": "The Industry School",
    "campus": "Sunshine Coast",
    "address": "170 Horton Parade, Maroochydore QLD",
    "area": "Sunshine Coast",
    "type": "Industry/vocational school",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 5357 8600",
    "website": "https://theindustryschool.com.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 21,
    "approximate": false,
    "mappable": true,
    "notes": "The PDF provides campus locations and contact details but does not state year levels on this page.",
    "geocodeQuery": "170 Horton Parade, Maroochydore QLD",
    "fallbackQuery": "",
    "shortName": "The Industry School – Sunshine Coast"
  },
  {
    "name": "Toogoolawa School",
    "campus": "Ormeau",
    "address": "138 Reedmans Rd, Ormeau QLD",
    "area": "Gold Coast",
    "type": "Alternative school",
    "minYear": 3,
    "maxYear": 10,
    "minAge": null,
    "maxAge": null,
    "gender": "Boys",
    "phone": "07 5547 5866",
    "website": "https://www.toogoolawa.com.au/",
    "delivery": [
      "In person"
    ],
    "sourcePage": 22,
    "approximate": false,
    "mappable": true,
    "notes": "For boys Years 3–10; class ratio 1:7; Australian Curriculum; character, social skills and self-esteem focus.",
    "geocodeQuery": "138 Reedmans Rd, Ormeau QLD",
    "fallbackQuery": "",
    "shortName": "Toogoolawa School – Ormeau"
  },
  {
    "name": "The Y / YMCA Vocational School",
    "campus": "Logan Junior Campus",
    "address": "53 Mary St, Kingston QLD",
    "area": "Logan",
    "type": "Vocational / alternative school",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3440 4322",
    "website": "https://ymcaqueensland.org.au/services/vocational-school",
    "delivery": [
      "In person"
    ],
    "sourcePage": 22,
    "approximate": false,
    "mappable": true,
    "notes": "Provides adjusted education programs and vocational training to secondary students. PDF notes several other campuses but does not list them here.",
    "geocodeQuery": "53 Mary St, Kingston QLD",
    "fallbackQuery": "",
    "shortName": "The Y / YMCA Vocational School – Logan Junior Campus"
  },
  {
    "name": "The Y / YMCA Vocational School",
    "campus": "Logan Senior Campus",
    "address": "41-45 Mary St, Kingston QLD",
    "area": "Logan",
    "type": "Vocational / alternative school",
    "minYear": null,
    "maxYear": null,
    "minAge": null,
    "maxAge": null,
    "gender": "Not stated",
    "phone": "07 3440 4300",
    "website": "https://ymcaqueensland.org.au/services/vocational-school",
    "delivery": [
      "In person"
    ],
    "sourcePage": 22,
    "approximate": false,
    "mappable": true,
    "notes": "Provides adjusted education programs and vocational training to secondary students. PDF notes several other campuses but does not list them here.",
    "geocodeQuery": "41-45 Mary St, Kingston QLD",
    "fallbackQuery": "",
    "shortName": "The Y / YMCA Vocational School – Logan Senior Campus"
  }
];
